#include "building_defs.h"

static const LedDef MOVIE_THEATER_LEDS[] = {
  { ZONE_STREET, ZF_EXTERIOR },
  { ZONE_STREET, ZF_EXTERIOR },
  { ZONE_INTERIOR, ZF_AMBIENT | ZF_SEASONAL },
  { ZONE_INTERIOR, ZF_AMBIENT | ZF_SEASONAL },
  { ZONE_INTERIOR, ZF_AMBIENT | ZF_SEASONAL },
  { ZONE_INTERIOR, ZF_AMBIENT | ZF_SEASONAL },
  { ZONE_INTERIOR, ZF_AMBIENT | ZF_SEASONAL },
  { ZONE_PROJECTOR, ZF_FEATURE },
  { ZONE_SIGNAGE, ZF_EXTERIOR | ZF_SEASONAL | ZF_FEATURE },
  { ZONE_SIGNAGE, ZF_EXTERIOR | ZF_SEASONAL | ZF_FEATURE },
  { ZONE_INTERIOR, ZF_NONE },
  { ZONE_INTERIOR, ZF_NONE },
  { ZONE_STREET, ZF_EXTERIOR },
  { ZONE_STREET, ZF_EXTERIOR },
};

extern const BuildingDef MOVIE_THEATER_DEF = {
  "MOVIE_THEATER",
  14,
  MOVIE_THEATER_LEDS
};
