#include "building_registry.h"
#include <cstring>

// ----------------------------------------------------------
// Extern declarations for generated building defs
// ----------------------------------------------------------
// These symbols are defined in src/buildings/*.cpp
// Generated by the Python tool
// ----------------------------------------------------------

extern const BuildingDef MOVIE_THEATER_DEF;
// extern const BuildingDef MODULAR_CAFE_DEF;
// extern const BuildingDef BOOKSHOP_DEF;
// extern const BuildingDef POLICE_STATION_DEF;

// ----------------------------------------------------------
// Registry table
// ----------------------------------------------------------

static const BuildingDef* ALL_BUILDINGS[] = {
  &MOVIE_THEATER_DEF,
  // &MODULAR_CAFE_DEF,
  // &BOOKSHOP_DEF,
  // &POLICE_STATION_DEF,
};

static const uint16_t BUILDING_COUNT =
  sizeof(ALL_BUILDINGS) / sizeof(ALL_BUILDINGS[0]);

// ----------------------------------------------------------
// Public API
// ----------------------------------------------------------

const BuildingDef* getBuildingDefById(const char* id) {
  if (!id) return nullptr;

  for (uint16_t i = 0; i < BUILDING_COUNT; i++) {
    if (strcmp(ALL_BUILDINGS[i]->id, id) == 0) {
      return ALL_BUILDINGS[i];
    }
  }
  return nullptr;
}

uint16_t getBuildingCount() {
  return BUILDING_COUNT;
}

const BuildingDef* getBuildingByIndex(uint16_t index) {
  if (index >= BUILDING_COUNT) return nullptr;
  return ALL_BUILDINGS[index];
}
